= Laws, Rules & Principles

== The Priciples of Object Oriented Desgin

=== Class Design

* The Single Responsibility Principle: A class should have one, and only one, reason to change.
* The Open Closed Principle: You should be able to extend a classes behavior, without modifying it.
* The Liskov Substitution Principle: Derived classes must be substitutable for their base classes.
* The Interface Segregation Principle: Make fine grained interfaces that are client specific.
* The Dependency Inversion Principle: Depend on abstractions, not on concretions.

=== Package Design

==== Cohesion

* The Release Reuse Equivalency Principle: The granule of reuse is the granule of release.
* The Common Closure Principle: Classes that change together are packaged together.
* The Common Reuse Principle: Classes that are used together are packaged together.

==== Coupling 

* The Acyclic Dependencies Principle: The dependency graph of packages must have no cycles.
* The Stable Dependencies Principle: Depend in the direction of stability.
* The Stable Abstractions Principle: Abstractness increases with stability.

== Robustness Principle

In computing, the robustness principle is a design guideline for software that states: "be conservative in what you do, be liberal in what you accept from others". It is often reworded as: "be conservative in what you send, be liberal in what you accept". The principle is also known as Postel's law, after Jon Postel, who used the wording in an early specification of TCP.

== Law of Demeter

The Law of Demeter (LoD) or principle of least knowledge is a design guideline for developing software, particularly object-oriented programs. In its general form, the LoD is a specific case of loose coupling. The guideline was proposed by Ian Holland at Northeastern University towards the end of 1987,[1] and can be succinctly summarized in each of the following ways:

* Each unit should have only limited knowledge about other units: only units "closely" related to the current unit.
* Each unit should only talk to its friends; don't talk to strangers.
* Only talk to your immediate friends.

== Conway’s Law

____
Any piece of software reflects the organizational structure that produced it.
____

Or even more clearly:

"Organizations which design systems are constrained to produce designs which are copies of the communication structures of these organizations."

== Abbreviations

=== ACID Definition
ACID is an acronym that stands for Atomicity, Consistency, Isolation, Durability. These are explained below.

==== Atomicity
Atomicity means that you guarantee that either all of the transaction succeeds or none of it does. You don’t get part of it succeeding and part of it not. If one part of the transaction fails, the whole transaction fails. With atomicity, it’s either “all or nothing”.

==== Consistency
This ensures that you guarantee that all data will be consistent. All data will be valid according to all defined rules, including any constraints, cascades, and triggers that have been applied on the database.

==== Isolation
Guarantees that all transactions will occur in isolation. No transaction will be affected by any other transaction. So a transaction cannot read data from any other transaction that has not yet completed. 

=== BASE

* Basic Availability: The database appears to work most of the time.
* Soft-state: Stores don’t have to be write-consistent, nor do different replicas have to be mutually consistent all the time.
* Eventual consistency: Stores exhibit consistency at some later point (e.g., lazily at read time).

=== CAP theorem

* Consistency: Every read receives the most recent write or an error
* Availability: Every request receives a (non-error) response, without the guarantee that it contains the most recent write
* Partition tolerance: The system continues to operate despite an arbitrary number of messages being dropped (or delayed) by the network between nodes

